### DISCUSSION TITLE
Metrics missing

### DISCUSSION THREAD

**Discussion by mihneamateihpe** [cybertec-postgresql/pgwatch2#808] [Q&A]
Hello,

I am facing a problem with my pgwatch2 metrics - some are missing. I am a number of metrics, but some important ones are table_stats and stat_statements. For table_stats I haven't looked much into it yet, but for stat_statements I've been trying for a while to make them work. The extension exists in the monitored db and in the env file and the pgwatch2 user is granted all the permissions (from the docs), however the metrics are missing from the http://ip:port/metrics curl. I've tried all sorts of modifications on the env file (at first I didn't even have an env file, as I did not think it was necessary). Below you can see the current service file & config file for pgwatch2. Logs are clear, no errors.

Thanks for your help!

------------------------------- service file below
```
[Unit]
Description=Pgwatch2 Gathering Daemon
After=network-online.target
# Uncomment the following line if PostgreSQL is required before starting Pgwatch2
# After=postgresql@12-main.service

[Service]
EnvironmentFile=/etc/pgwatch2/pgwatch2.yaml
User=postgres
Type=notify
ExecStart=pgwatch2-daemon --host=10.96.130.179 --user=pgwatch2 --dbname=pgwatch2 --password=pgwatch2 --datastore=prometheus >> /var/log/pgwatch2.log 2>&1
StandardOutput=file:/var/log/pgwatch2.log
StandardError=file:/var/log/pgwatch2.log
Restart=on-failure
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target

```
--------------------------- config file below
```
metric_store_conn_str: "postgresql://pgwatch2:secret@metric_db_conn_ip:5432/pgwatch2_metric"
min_db_size_mb: 1
pg_retention_days: 7
enable_pg_stat_statements: true
enable_pg_stat_activity: true
enable_pg_stat_database: true
enable_pg_stat_tables: true

metrics:
  pg_stat_statements:
    file: /etc/pgwatch2/metrics/00_helpers/get_stat_statements/15/metric.sql
    interval: '30s'
    dbnames: ['realtimedb']

monitored_databases:
  - name: "realtimedb"
    host: "localhost"
    port: 5432
    user: "pgwatch2"
    password: "pgwatch2"
    dbname: "realtimedb"
    sslmode: "disable"
    preset_configs: ["basic", "pg_stat_statements"]
  - name: "postgres"
    host: "localhost"
    port: 5432
    user: "pgwatch2"
    password: "pgwatch2"
    dbname: "postgres"
    sslmode: "disable"
    preset_configs: ["basic", "pg_stat_statements"]
```
