### ISSUE TITLE
pgwatch2 memory leak

### ISSUE THREAD

**Issue by deric** [cybertec-postgresql/pgwatch2#146]
`pgwatch2` is leaking tens of GB of memory in a couple of hours:
```
Out of memory: Kill process 22804 (pgwatch2) score 683 or sacrifice child
kernel: Killed process 22804 (pgwatch2) total-vm:24539728kB, anon-rss:23037924kB, file-rss:0kB, shmem-rss:0kB
```
I'm trying to monitor a single DB instance using a subset of `full` preset:
```
  custom_metrics:
    archiver: 60
    backends: 60
    bgwriter: 60
    change_events: 300
    db_size: 300
    db_stats: 60
    index_stats: 600
    kpi: 120
    locks: 60
    locks_mode: 60
    replication: 120
    replication_slots: 120
    sproc_stats: 180
    stat_statements: 180
    stat_statements_calls: 60
    table_bloat_approx_summary: 7200
    table_io_stats: 180
    table_stats: 180
    wal: 60
    wal_size: 120
```
