### ISSUE TITLE
pgwatch2 and k8s

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#168]
hello trying to execute pgwatch2 in k8s : 
i use the file  in the sample k8s with

```
            env: 
              - name: PW2_PGHOST
                value: europe.
              - name: PW2_PGPORT
                value: "5432"
              - name: PW2_PGDATABASE
                value: pgwatch2
              - name: PW2_PGUSER
                value: pgwatch2
              - name: PW2_PGPASSWORD
                value: mypassword
              - name: PW2_GRAFANA_BASEURL
                value: http://grafana.10.42.8.177.xip.io
              - name: PW2_DATASTORE
                value: postgres
              - name: PW2_PG_METRIC_STORE_CONN_STR
                value: postgresql://pgwatch2:pgwatch2@mydbpgsql:5432/pgwatch2
```

and the logs
 
```
writing new private key to '/pgwatch2/persistent-config/self-signed-ssl.key'
-----
CREATE ROLE
GRANT ROLE
CREATE DATABASE
CREATE DATABASE
CREATE DATABASE
CREATE SCHEMA
CREATE EXTENSION
CREATE EXTENSION
SET
psql:/pgwatch2/sql/config_store/config_store.sql:13: NOTICE:  table "preset_config" does not exist, skipping
ALTER DATABASE
SET
DROP TABLE
CREATE TABLE
psql:/pgwatch2/sql/config_store/config_store.sql:23: NOTICE:  table "monitored_db" does not exist, skipping
DROP TABLE
CREATE TABLE
CREATE INDEX
ALTER TABLE
CREATE TABLE
CREATE TABLE
INSERT 0 1
INSERT 0 8
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
CREATE SCHEMA
GRANT
psql:/pgwatch2/sql/metric_store/00_schema_base.sql:17: WARNING:  NB! Enabling asynchronous commit for pgwatch2 role - revert if possible data loss on crash is not acceptable!
DO
SET
CREATE TABLE
COMMENT
CREATE INDEX
CREATE TABLE
CREATE FUNCTION
GRANT
RESET
CREATE FUNCTION
GRANT
CREATE FUNCTION
GRANT
CREATE FUNCTION
GRANT
CREATE FUNCTION
GRANT
CREATE FUNCTION
GRANT
CREATE SCHEMA
CREATE EXTENSION
SET
CREATE TABLE
COMMENT
CREATE INDEX
CREATE INDEX
RESET
INSERT 0 1
CREATE FUNCTION
GRANT
BEGIN
CREATE FUNCTION
GRANT
COMMENT
COMMIT
psql:/pgwatch2/sql/metric_fetching_helpers/stat_statements_wrapper.sql:54: NOTICE:  extension "pg_stat_statements" already exists, skipping
DO
DO
GRANT
COMMENT
BEGIN
CREATE EXTENSION
DO
COMMIT
CREATE FUNCTION
GRANT
COMMENT
CREATE FUNCTION
GRANT
COMMENT
CREATE FUNCTION
GRANT
COMMENT
CREATE FUNCTION
GRANT
COMMENT
CREATE FUNCTION
GRANT
COMMENT
2019-08-01 16:03:39,451 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-08-01 16:03:39,460 INFO RPC interface 'supervisor' initialized
2019-08-01 16:03:39,460 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-08-01 16:03:39,460 INFO supervisord started with pid 1
2019-08-01 16:03:40,464 INFO spawned: 'postgres' with pid 250
2019-08-01 16:03:40,466 INFO spawned: 'pgwatch2' with pid 251
2019-08-01 16:03:40,469 INFO spawned: 'webpy' with pid 252
2019-08-01 16:03:40,473 INFO spawned: 'grafana' with pid 253
2019-08-01 16:03:40,475 INFO spawned: 'grafana_dashboard_setup' with pid 257
2019-08-01 16:03:40,545 INFO success: postgres entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-08-01 16:03:40,545 INFO success: grafana entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-08-01 16:03:40,546 INFO success: grafana_dashboard_setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-08-01 16:03:40,571 INFO exited: grafana (exit status 1; not expected)
2019-08-01 16:03:40,809 INFO spawned: 'grafana' with pid 288
2019-08-01 16:03:40,810 INFO exited: pgwatch2 (exit status 1; not expected)
2019-08-01 16:03:40,811 INFO success: grafana entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-08-01 16:03:41,468 INFO success: webpy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-01 16:03:41,815 INFO spawned: 'pgwatch2' with pid 317
2019-08-01 16:03:41,847 INFO exited: pgwatch2 (exit status 1; not expected)
2019-08-01 16:03:43,879 INFO spawned: 'pgwatch2' with pid 415
2019-08-01 16:03:43,976 INFO exited: pgwatch2 (exit status 1; not expected)
2019-08-01 16:03:45,358 INFO exited: grafana_dashboard_setup (exit status 0; expected)
2019-08-01 16:03:47,363 INFO spawned: 'pgwatch2' with pid 714
2019-08-01 16:03:48,393 INFO success: pgwatch2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-01 16:03:48,394 INFO exited: pgwatch2 (exit status 1; not expected)
2019-08-01 16:03:49,397 INFO spawned: 'pgwatch2' with pid 725
(...)

2019-08-01 16:05:12,019 INFO spawned: 'pgwatch2' with pid 1221
2019-08-01 16:05:12,050 INFO exited: pgwatch2 (exit status 1; not expected)
2019-08-01 16:05:15,054 INFO spawned: 'pgwatch2' with pid 1232
2019-08-01 16:05:15,081 INFO exited: pgwatch2 (exit status 1; not expected)
2019-08-01 16:05:16,083 INFO gave up: pgwatch2 entered FATAL state, too many start retries too quickly
```
