### ISSUE TITLE
PW2_VERBOSE not working

### ISSUE THREAD

**Issue by rockaut** [cybertec-postgresql/pgwatch2#215]
I'm trying to debug a not working docker (with file based config) deployment but the PW2_VERBOSE isn't giving me any more logs than without env variable.

```
version: '2.2'

volumes:
  configs:

services:
  pgwatch2:
    image: cybertec/pgwatch2-nonroot
    environment:
      - PW2_CONFIG=/pgwatch2/config
      - PW2_METRICS_FOLDER=/pgwatch2/metrics
      - PW2_VERBOSE=vvv
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - configs:/pgwatch2/config
```
