### ISSUE TITLE
[Feature] Secrets in file based configs

### ISSUE THREAD

**Issue by rockaut** [cybertec-postgresql/pgwatch2#216]
It would be great if we could use secrets - or more specifically - env variables in file base configs.

So for example, we create a secret with 3 keys ( db-name, db-password, db-user ) and then we want to use that secrets in the file based configs:

```
apiVersion: v1
        data:
          db-name: base64hash
          db-password: base64hash
          db-user: base64hash
        kind: Secret
        metadata:
          annotations:
            template.openshift.io/expose-database_name: '{.data[''db-name'']}'
            template.openshift.io/expose-password: '{.data[''db-password'']}'
            template.openshift.io/expose-username: '{.data[''db-user'']}'
          labels:
            app: db-instance
            template: db-instance
          name: db-instance
          namespace: postgresql-test
        type: Opaque
```

```
- env:
    - name: POSTGRESQL_USER
       valueFrom:
       secretKeyRef:
       key: db-user
       name: db-instance
    - name: POSTGRESQL_PASSWORD
       valueFrom:
       secretKeyRef:
       key: db-password
       name: db-instance
    - name: POSTGRESQL_DATABASE
       valueFrom:
       secretKeyRef:
       key: db-name
       name: db-instance
```

```
apiVersion: v1
    kind: ConfigMap
    metadata:
    namespace: postgresql-test
    name: db-instance
    labels:
      app: db-instance
    data:
      initial.md: 'just for initialization'
      mds3.yaml: |-
        - unique_name: test-instance
          dbtype: postgres-continuous-discovery
          host: test-instance
          port: 5432
          dbname: ${POSTGRESQL_DATABASE}
          user: ${POSTGRESQL_USER}
          password: ${POSTGRESQL_PASSWORD}
          sslmode: disable
          stmt_timeout: 5
          is_superuser: false
          preset_metrics: full
          is_enabled: true
          group: testing
```

Beyond this specific use case it could be usefull for other things too :D
