### ISSUE TITLE
No preset configurations in management web ui

### ISSUE THREAD

**Issue by gram7gram** [cybertec-postgresql/pgwatch2#30]
I failed to understand how to enable same dashboard metrics, as in example.

By default, I have not presets at `localhost:15433/dbs` and I have no idea of what to write in `custom config`.

So, `localhost:15434/dashboard/db/db-overview?orgId=1` yields `N/A`.

From what I understood, when new entry is added in management ui, it will be possible to select this entry in dashboard.

Please, provide me with custom config example, or teach where to get presets.

docker-compose.yml
```yml
    pw2:
        container_name: pw2
        image: cybertec/pgwatch2
        ports:
            - 15433:8080 #Management
            - 15434:3000 #Dashboard
        environment:
            NOTESTDB: 1
            PW2_PGHOST: psql-master
            PW2_PGPORT: 5432
            PW2_PGDATABASE: dev
            PW2_PGUSER: pgwatch2
            PW2_PGPASSWORD: 12345

    psql-master:
        container_name: psql-master
        hostname: psql-master
        image: postgres:9.3-alpine
        ports:
            - 5433:5432
        volumes:
            ...
        environment:
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
```

**Comment by gram7gram** [comment]
Started raw container, without `environment`, to check if presets are available.

Yes, they are!

```yml
pw2:
        container_name: pw2
        image: cybertec/pgwatch2
        ports:
            - 15433:8080 #Management
            - 15434:3000 #Dashboard
```
