### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#575]
Hi,

i do not understand
```yaml
postgresql:
  user: &postgresuser pgwatch2
  password: &postgrespassword pgwatch2
```

what is &postgresuser for ?

thx
