### ISSUE TITLE
feat : need extraVolumes

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#632]
To use the env var pw2_config (for monitored dbs) i need  to mount a new volume in daemon container

so i propose to add
```yaml
          {{- if .Values.daemon.extraVolumeMounts }}
            {{- .Values.daemon.extraVolumeMounts | toYaml | nindent 12 }}
          {{- end }}
``` 

and 
```yaml
      volumes:
        - name: config-volume
          configMap:
            name: pgwatch2-config
            optional: true
      {{- if .Values.daemon.extraVolumes }}
        {{- .Values.daemon.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
```
