### ISSUE TITLE
Automatic rollout of helpers not working as expected in Docker Compose setup

### ISSUE THREAD

**Issue by anshibanov** [cybertec-postgresql/pgwatch2#677]
I am running pgwatch2 using docker-compose with the following configuration:

```yaml
  pgwatch2-daemon:
    image: cybertec/pgwatch2-daemon:latest
    container_name: pgwatch2-exporter
    volumes:
      - /opt/monitoring-stack/pgwatch2/metrics.yml:/metrics.yml
    environment:
      - PW2_VERBOSE=info
      - PW2_DATASTORE=prometheus
      - PW2_CONFIG=/metrics.yml
      - PGPASSWORD
```

Here is how my metrics.yml looks:
```yaml
- unique_name: test
  dbtype: postgres-continuous-discovery  
  host: 192.168.0.1
  port: 5432
  user: pgwatch2
  password: $PGPASSWORD
  sslmode: disable   
  stmt_timeout: 5
  is_superuser: true
  preset_metrics: prometheus 
  custom_metrics:   
  preset_metrics_standby: 
  custom_metrics_standby:
  dbname_include_pattern: 
  dbname_exclude_pattern:
  is_enabled: true
  group: default
  sslrootcert: ''
  sslcert: ''
  sslkey: ''
```

According to the [documentation](https://pgwatch2.readthedocs.io/en/latest/preparing_databases.html#automatic-rollout-of-helpers), I expect pgwatch2 to automatically create helper functions (since the user pgwatch2 has superuser privileges in Postgres). However, this doesn't happen, and I see the following in the logs:

```
2023/08/29 18:03:37 WARN main: --metrics-folder path not specified, using /pgwatch2/metrics
2023/08/29 18:03:37 INFO main: Starting the internal statistics interface on port 8081...
...
2023/08/29 18:04:04 WARN FetchMetrics: [te-data:stat_statements_calls] Skipping actual fetch as prerequisite extension 'pg_stat_statements' not present
2023/08/29 18:04:04 INFO FetchMetrics: [te-data:cpu_load] failed to fetch metrics: pq: function get_load_average() does not exist
```

Why pgwatch does not create  function get_load_average() ?
