### ISSUE TITLE
Problem with PW2_GRAFANASSL

### ISSUE THREAD

**Issue by gbaptista** [cybertec-postgresql/pgwatch2#73]
Looking at `tail -f /var/log/grafana/grafana.log` inside container:
```
Startup failed" error="Fail to start server. error: Cannot find SSL cert_file at /pgwatch2/self-signed-ssl.pem
```

For some reason, grafana is trying to find out `self-signed-ssl.pem` inside `/pgwatch2` instead of `/pgwatch2/persistent-config`.

My workaround: create the keys in the correct directory.

`docker-compose.yml`:
```yaml
version: '3'
services:
  pw2:
    build: ./
    volumes:
      - './pg:/var/lib/postgresql'
      - './influx:/var/lib/influxdb'
      - './grafana:/var/lib/grafana'
      - './pw2:/pgwatch2/persistent-config'
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - "PW2_GRAFANASSL=1"
      - "PW2_WEBSSL=1"
```
`Dockerfile`:
```dockerfile
FROM cybertec/pgwatch2

RUN cd /pgwatch2 && \
    openssl req -x509 -newkey rsa:4096 \
    -keyout /pgwatch2/self-signed-ssl.key \
    -out /pgwatch2/self-signed-ssl.pem \
    -days 3650 -nodes -sha256 -subj '/CN=pw2'

RUN chown grafana:grafana /pgwatch2/self-signed-ssl.key
RUN chown grafana:grafana /pgwatch2/self-signed-ssl.pem
RUN chmod -R 0600 /pgwatch2/self-signed-ssl.key
RUN chmod -R 0600 /pgwatch2/self-signed-ssl.pem

CMD ["/pgwatch2/docker-launcher.sh"]
```
